### ISSUE TITLE
Problem with setting up scipy after update

### ISSUE THREAD

**Issue by jmatsushita** [ImaginationForPeople/assembl#27]
I backed up, git pulled and after running ```fab devenv app_compile``` the update requirements task failed with:

```
[localhost] out:   Running setup.py install for scipy
[localhost] out:     Complete output from command /home/assembl/assembl/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3SlEnT/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-i9TODO-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/assembl/assembl/venv/include/site/python2.7/scipy:
[localhost] out:     lapack_opt_info:
[localhost] out:     openblas_lapack_info:
[localhost] out:       libraries openblas not found in ['/home/assembl/assembl/venv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     lapack_mkl_info:
[localhost] out:     mkl_info:
[localhost] out:       libraries mkl,vml,guide not found in ['/home/assembl/assembl/venv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     atlas_3_10_threads_info:
[localhost] out:     Setting PTATLAS=ATLAS
[localhost] out:       libraries tatlas,tatlas not found in /home/assembl/assembl/venv/lib
[localhost] out:       libraries lapack_atlas not found in /home/assembl/assembl/venv/lib
[localhost] out:       libraries tatlas,tatlas not found in /usr/local/lib
[localhost] out:       libraries lapack_atlas not found in /usr/local/lib
[localhost] out:       libraries tatlas,tatlas not found in /usr/lib
[localhost] out:       libraries lapack_atlas not found in /usr/lib
[localhost] out:       libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
[localhost] out:       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
[localhost] out:     numpy.distutils.system_info.atlas_3_10_threads_info
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     atlas_3_10_info:
[localhost] out:       libraries satlas,satlas not found in /home/assembl/assembl/venv/lib
[localhost] out:       libraries lapack_atlas not found in /home/assembl/assembl/venv/lib
[localhost] out:       libraries satlas,satlas not found in /usr/local/lib
[localhost] out:       libraries lapack_atlas not found in /usr/local/lib
[localhost] out:       libraries satlas,satlas not found in /usr/lib
[localhost] out:       libraries lapack_atlas not found in /usr/lib
[localhost] out:       libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
[localhost] out:       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
[localhost] out:     numpy.distutils.system_info.atlas_3_10_info
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     atlas_threads_info:
[localhost] out:     Setting PTATLAS=ATLAS
[localhost] out:       libraries ptf77blas,ptcblas,atlas not found in /home/assembl/assembl/venv/lib
[localhost] out:       libraries lapack_atlas not found in /home/assembl/assembl/venv/lib
[localhost] out:       libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
[localhost] out:       libraries lapack_atlas not found in /usr/local/lib
[localhost] out:       libraries ptf77blas,ptcblas,atlas not found in /usr/lib
[localhost] out:       libraries lapack_atlas not found in /usr/lib
[localhost] out:       libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
[localhost] out:       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
[localhost] out:     numpy.distutils.system_info.atlas_threads_info
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     atlas_info:
[localhost] out:       libraries f77blas,cblas,atlas not found in /home/assembl/assembl/venv/lib
[localhost] out:       libraries lapack_atlas not found in /home/assembl/assembl/venv/lib
[localhost] out:       libraries f77blas,cblas,atlas not found in /usr/local/lib
[localhost] out:       libraries lapack_atlas not found in /usr/local/lib
[localhost] out:       libraries f77blas,cblas,atlas not found in /usr/lib
[localhost] out:       libraries lapack_atlas not found in /usr/lib
[localhost] out:       libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
[localhost] out:       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
[localhost] out:     numpy.distutils.system_info.atlas_info
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     /home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:1505: UserWarning:
[localhost] out:         Atlas (http://math-atlas.sourceforge.net/) libraries not found.
[localhost] out:         Directories to search for the libraries can be specified in the
[localhost] out:         numpy/distutils/site.cfg file (section [atlas]) or by setting
[localhost] out:         the ATLAS environment variable.
[localhost] out:       warnings.warn(AtlasNotFoundError.__doc__)
[localhost] out:     lapack_info:
[localhost] out:       libraries lapack not found in ['/home/assembl/assembl/venv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     /home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:1516: UserWarning:
[localhost] out:         Lapack (http://www.netlib.org/lapack/) libraries not found.
[localhost] out:         Directories to search for the libraries can be specified in the
[localhost] out:         numpy/distutils/site.cfg file (section [lapack]) or by setting
[localhost] out:         the LAPACK environment variable.
[localhost] out:       warnings.warn(LapackNotFoundError.__doc__)
[localhost] out:     lapack_src_info:
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     /home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:1519: UserWarning:
[localhost] out:         Lapack (http://www.netlib.org/lapack/) sources not found.
[localhost] out:         Directories to search for the sources can be specified in the
[localhost] out:         numpy/distutils/site.cfg file (section [lapack_src]) or by setting
[localhost] out:         the LAPACK_SRC environment variable.
[localhost] out:       warnings.warn(LapackSrcNotFoundError.__doc__)
[localhost] out:       NOT AVAILABLE
[localhost] out:     
[localhost] out:     Running from scipy source directory.
[localhost] out:     Traceback (most recent call last):
[localhost] out:       File "<string>", line 1, in <module>
[localhost] out:       File "/tmp/pip-build-3SlEnT/scipy/setup.py", line 253, in <module>
[localhost] out:         setup_package()
[localhost] out:       File "/tmp/pip-build-3SlEnT/scipy/setup.py", line 250, in setup_package
[localhost] out:         setup(**metadata)
[localhost] out:       File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
[localhost] out:         config = configuration()
[localhost] out:       File "/tmp/pip-build-3SlEnT/scipy/setup.py", line 175, in configuration
[localhost] out:         config.add_subpackage('scipy')
[localhost] out:       File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
[localhost] out:         caller_level = 2)
[localhost] out:       File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
[localhost] out:         caller_level = caller_level + 1)
[localhost] out:       File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
[localhost] out:         config = setup_module.configuration(*args)
[localhost] out:       File "scipy/setup.py", line 15, in configuration
[localhost] out:         config.add_subpackage('linalg')
[localhost] out:       File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
[localhost] out:         caller_level = 2)
[localhost] out:       File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
[localhost] out:         caller_level = caller_level + 1)
[localhost] out:       File "/home/assembl/assembl/venv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
[localhost] out:         config = setup_module.configuration(*args)
[localhost] out:       File "scipy/linalg/setup.py", line 19, in configuration
[localhost] out:         raise NotFoundError('no lapack/blas resources found')
[localhost] out:     numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
[localhost] out:     
[localhost] out:     ----------------------------------------
[localhost] out: Command "/home/assembl/assembl/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3SlEnT/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-i9TODO-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/assembl/assembl/venv/include/site/python2.7/scipy" failed with error code 1 in /tmp/pip-build-3SlEnT/scipy
```

**Comment by maparent** [comment]
re-run `fab devenv install_builddeps`.
We still need a process to automate this (rare) case.
